spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
    alicloud:
      access-key: LTAI5tRi6o9D4LmB5CcQitUN
      secret-key: in4q01WU8Ex6DYN5cuQQPPWX3FKyw5
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-chenfl
      sms:
        accessKeyId: NOlCriukaUkvlm8X
        secret: zpXIJIbEVO7rWuUu8rEMbImu0srNeV
        signName: 同行者
        templateCode: SMS_107070058

  application:
    name: gulimall-third-party

  #    链路追踪
  zipkin:
    base-url: http://192.168.56.10:9411/    # zipkin 服务器的地址 # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web    # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1    # 设置抽样采集率为100%，默认为0.1，即10%

server:
  port: 30000
